# Generated by Django 5.1.4 on 2025-02-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_ticket'),
    ]

    operations = [
    ]
